# Generated by Django 2.2 on 2019-05-06 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('create_time', models.DateField(default=django.utils.timezone.now)),
                ('update_time', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'BlogCategory',
            },
        ),
        migrations.CreateModel(
            name='TagModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='标签名')),
                ('create_time', models.DateField(default=django.utils.timezone.now)),
                ('update_time', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'BlogTag',
            },
        ),
        migrations.CreateModel(
            name='ArticleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('body', models.TextField()),
                ('views', models.PositiveIntegerField(default=0)),
                ('create_time', models.DateField(default=django.utils.timezone.now)),
                ('update_time', models.DateField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('cate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.CategoryModel')),
                ('tags', models.ManyToManyField(blank=True, to='article.TagModel', verbose_name='标签集合')),
            ],
            options={
                'db_table': 'BlogArticle',
            },
        ),
    ]
